/* Python Akademisi: script.js dosyasından önce yüklenir. */
function mkCards(items) {
  return items.map(([front, back, code]) => ({ front, back, code }));
}

function mkQuiz(items) {
  return items.map(([q, options, correct, explain]) => ({ q, options, correct, explain }));
}

const esc = (value) => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function codeBlock(source) {
  return `<pre><code class="language-python">${esc(source)}</code></pre>`;
}

function lessonFor(m) {
  const [one, two, three, four, five] = m.examples;
  return `<h3>${m.title}</h3>
<p><strong>${m.title}</strong>, Python ile üretim yapan bir geliştiricinin yalnızca sözdizimini değil, kararlarını da açıklayabilmesini gerektirir. Bu derste <code>${m.term}</code> kavramını küçük, ölçülebilir örneklerle ele alacağız. Amaç kopyala-yapıştır yapmak değil; girdinin, ara durumların ve çıktının nasıl ilişkilendiğini izlemektir. Her örneği laboratuvarda çalıştırın, bir değeri değiştirin ve sonucun neden değiştiğini kendi cümlelerinizle yazın.</p>
<h4>Problemi modelleme</h4>
<p>İyi Python kodu önce problemi sadeleştirir. ${m.focus} Bir çözüm yazmadan önce hangi bilginin değişken, hangisinin sabit, hangi durumun hata olduğunu belirleyin. İsimler niyeti taşımalıdır: <code>x</code> yerine <code>toplam_puan</code>, <code>d</code> yerine <code>kullanici_verisi</code> kullanmak bakım maliyetini düşürür. Küçük fonksiyonlar, açık veri akışı ve doğrulanabilir ara sonuçlar; karmaşık sistemlerde tesadüfi başarıdan daha değerlidir.</p>
${codeBlock(one)}
<h4>Adım adım okuma</h4>
<p>Örnekteki her satırı bir durum değişimi olarak okuyun. Önce veri oluşturulur, sonra <strong>${m.term}</strong> üzerinde bir işlem yapılır ve en sonunda sonuç görünür olur. Hata ayıklarken doğrudan büyük fonksiyona bakmak yerine ara değerleri <code>print()</code> ile gözlemleyin. Gerçek uygulamalarda bunu yapılandırılmış günlükleme ile yaparsınız; eğitim ortamında ise görünür ara çıktı zihinsel modelinizi test etmek için yeterlidir. Beklenti ile gerçek çıktı farklıysa varsayımınızı düzeltin.</p>
${codeBlock(two)}
<h4>Sağlam ve okunabilir çözüm</h4>
<p>${m.detail} Kodun çalışması tek başına kalite ölçütü değildir. Aynı kodun altı ay sonra bir ekip arkadaşı tarafından anlaşılması, sınır durumlarda davranışının tahmin edilebilir olması ve değişikliğe direnç göstermemesi gerekir. Bu nedenle birden fazla işi aynı satıra sıkıştırmak yerine anlamlı ara değişkenler kullanın. Girdi doğrulamasını hesaplamadan ayırın; mümkünse saf fonksiyonlar yazın ve dönüş değerini açıkça kullanın.</p>
${codeBlock(three)}
<div class="lesson-tip">💡 Önce örneği olduğu gibi çalıştırın; sonra yalnızca tek bir değeri değiştirip çıktıyı tahmin edin. Tahmin etmek pasif okumadan çok daha kalıcı öğrenme sağlar.</div>
<h4>Sınır durumları ve test düşüncesi</h4>
<p>Profesyonel geliştirmede en pahalı hatalar çoğunlukla normal akışta değil, boş veri, beklenmeyen tip, tekrar eden kayıt veya sınır değerlerde çıkar. ${m.risk} Bu yüzden “mutlu yol” örneğinin yanına en az bir karşı örnek ekleyin. Bir işlev için giriş, beklenen sonuç ve hata davranışı yazmak küçük bir test planıdır. Bu alışkanlık, framework veya araç değişse bile taşınan temel bir mühendislik becerisidir.</p>
${codeBlock(four)}
<div class="lesson-warn">⚠ ${m.warning} Geniş bir <code>except</code>, sessiz dönüşüm veya gizli varsayım kısa vadede rahat görünse de hatayı daha uzağa taşır.</div>
<h4>Gerçek projeye taşıma</h4>
<p>${m.project} Üretim kodunda bu akışı birim testleri, anlamlı hata mesajları ve küçük sorumluluklara ayrılmış modüllerle destekleyin. Dokümantasyonu sadece ilk kurulumda değil, sürüm yükseltirken de kontrol edin. Ayrıca performans sorununu ölçmeden optimizasyon yapmayın: önce doğru ve okunur çözümü kurun, sonra darboğazı veriye dayanarak iyileştirin. Böylece araçlara bağımlı olmayan, sürdürülebilir bir çalışma biçimi edinirsiniz.</p>
${codeBlock(five)}
<div class="lesson-practice">🎯 Görev: ${m.practice} Çözümünüz için normal, boş ve sınır değer içeren üç farklı girdi deneyin; her birinin beklenen çıktısını yorum satırı olarak yazın.</div>
<h4>Özet ve sonraki adım</h4>
<p>Bu modülün ana fikri şudur: <strong>${m.term}</strong> bir ezber konusu değil, kontrollü veri akışı kurma aracıdır. Küçük örnekleri değiştirerek çalışın, isimleri iyileştirin ve hata senaryolarını görünür kılın. Bir sonraki modüle geçmeden önce laboratuvardaki başlangıç kodunu kendi örneğinize dönüştürün; ardından kartları tekrar edip testte yalnızca doğru seçeneği değil, diğer seçeneklerin neden yanlış olduğunu da açıklayın.</p>`;
}

function cardsFor(m) {
  return mkCards([
    [`${m.title} nedir?`, m.short, `print("${m.term}")`],
    [`${m.term} kullanırken ilk adım?`, "Girdiyi ve beklenen çıktıyı açıkça tanımlamaktır.", "veri = [1, 2, 3]\nprint(veri)"],
    ["Okunabilir isimlendirme neden önemlidir?", "Kodun niyetini görünür yapar ve bakımı kolaylaştırır.", "toplam_puan = 42"],
    ["Sınır durumuna örnek nedir?", "Boş veri, sıfır, eksik alan veya beklenmeyen tip.", "sayilar = []\nprint(len(sayilar))"],
    ["Ara çıktıları incelemek için ne kullanılabilir?", "Eğitim sırasında print() ile değerler gözlemlenebilir.", "sonuc = 2 + 3\nprint(sonuc)"],
    ["Saf fonksiyonun yararı nedir?", "Aynı girdiyle aynı sonucu verir; test etmesi kolaydır.", "def iki_kat(n):\n    return n * 2"],
    ["Küçük fonksiyonlar neden tercih edilir?", "Tek sorumluluk taşır, okunur ve yeniden kullanılır.", "def temizle(metin):\n    return metin.strip()"],
    ["Önce ne optimize edilmelidir?", "Önce doğruluk ve açıklık; performans ölçümden sonra ele alınır.", "print('önce doğru çözüm')"],
    [`${m.term} için güvenli alışkanlık?`, "Varsayımları test etmek ve hata davranışını görünür kılmaktır.", "assert 2 + 2 == 4"],
  ]);
}

function quizFor(m) {
  return mkQuiz([
    [`${m.title} çalışırken öncelik nedir?`, ["Tahmin etmek", "Girdi ve çıktıyı tanımlamak", "Kodun adını kısaltmak", "Her hatayı gizlemek"], 1, "Doğru model, açık girdi ve çıktıyla başlar."],
    ["Python'da yorum satırı nasıl başlar?", ["//", "#", "--", "/*"], 1, "# tek satır yorum başlatır."],
    ["len([]) sonucu nedir?", ["0", "1", "None", "Hata"], 0, "Boş listenin eleman sayısı sıfırdır."],
    ["Okunabilir kod için hangisi daha iyidir?", ["a", "toplam_siparis", "z9", "_"], 1, "Anlamlı isim, niyeti açıklar."],
    ["assert ifadesinin rolü nedir?", ["Ekranı temizler", "Beklentiyi denetler", "Dosya açar", "Döngüyü sonsuz yapar"], 1, "assert koşulun doğru olmasını bekler."],
    ["Bir hata yalnızca boş girdide oluyorsa bu neyi gösterir?", ["Sınır durumu", "Başarılı test", "Sözdizimi rengi", "Yorum satırı"], 0, "Boş değerler tipik sınır durumlarıdır."],
    ["print() eğitimde en çok ne için yararlıdır?", ["Paket kurmak", "Ara değer gözlemek", "Sınıf silmek", "Sunucu başlatmak"], 1, "Ara çıktılar veri akışını görünür kılar."],
    ["Test edilebilir fonksiyonun önemli özelliği nedir?", ["Birden çok iş yapması", "Açık giriş ve dönüşü olması", "Her hatayı yutması", "Global veriye bağlı olması"], 1, "Açık sözleşme test yazmayı kolaylaştırır."],
    [`${m.term} örneğini geliştirmenin iyi yolu nedir?`, ["Çıktıyı hiç okumamak", "Tek değeri değiştirip sonucu tahmin etmek", "Tüm değişkenleri tek harf yapmak", "Hata mesajlarını kaldırmak"], 1, "Kontrollü değişiklik aktif öğrenme sağlar."],
  ]);
}

const M = (key, title, term, short, focus, detail, risk, warning, project, practice, starter, examples) =>
  ({ key, title, term, short, focus, detail, risk, warning, project, practice, starter, examples });

const MODULES = [
  M("data", "Temel Python Objeleri ve Veri Yapıları", "list, tuple, dict ve set", "Python'un temel veri taşıyıcılarıdır.", "Koleksiyon seçimi verinin değişebilirliği ve erişim biçimine göre yapılır.", "Liste sıralıdır ve değişir; tuple sabittir; sözlük anahtarla erişir; set tekrarı kaldırır.", "Boş anahtara erişim veya yanlış veri tipine göre işlem yapma sık rastlanır.", "Sözlükte doğrudan anahtar erişimi KeyError üretebilir; gerekirse get() kullanın.", "Kullanıcı profili, sepet ve etiket verilerini doğru koleksiyonla modelleyebilirsiniz.", "Bir öğrenci sözlüğü oluşturun, iki ders notu ekleyin ve ortalamayı hesaplayın.", "ogrenci = {'ad': 'Ece', 'notlar': [80, 90]}\nprint(sum(ogrenci['notlar']) / len(ogrenci['notlar']))", ["meyveler = ['elma', 'armut']\nmeyveler.append('kiraz')\nprint(meyveler)", "konum = (41.0, 29.0)\nprint(konum[0])", "kullanici = {'ad': 'Ayşe', 'xp': 120}\nprint(kullanici.get('xp', 0))", "etiketler = {'python', 'web', 'python'}\nprint(etiketler)", "for anahtar, deger in kullanici.items():\n    print(anahtar, deger)"]),
  M("conditionals", "Koşullu Durumlar", "if, elif ve else", "Program akışını koşullara göre dallandırır.", "Karar ağacını en özel koşuldan genel koşula kurmak gerekir.", "Karşılaştırma, mantıksal operatörler ve truthy/falsy değerler karar mekanizmasının temelidir.", "Sıralaması yanlış koşullar ulaşılmaz dallar oluşturabilir.", "Atama için =, karşılaştırma için == kullanılır; girinti Python sözdiziminin parçasıdır.", "Yetkilendirme, indirim ve form doğrulama akışları kurabilirsiniz.", "Puanı alan ve AA, BB veya CC yazdıran bir notlandırıcı yazın.", "puan = 76\nif puan >= 70:\n    print('Başarılı')\nelse:\n    print('Tekrar dene')", ["puan = 85\nif puan >= 90:\n    notu = 'AA'\nelif puan >= 70:\n    notu = 'BB'\nelse:\n    notu = 'CC'\nprint(notu)", "yas = 20\nprint('yetişkin' if yas >= 18 else 'çocuk')", "kullanici = ''\nif not kullanici:\n    print('Ad gerekli')", "stok = 3\nif stok > 0 and stok < 10:\n    print('Az stok')", "rol = 'editor'\nif rol in ('admin', 'editor'):\n    print('İzin verildi')"]),
  M("loops", "Döngü Yapıları", "for ve while", "Tekrarlanan işleri kontrollü biçimde yürütür.", "Iterable üzerinde for, koşula dayalı tekrar için while seçilir.", "range, enumerate, break ve continue döngü davranışını açık biçimde yönetir.", "Sayaç güncellenmeyen while döngüsü sonsuza gidebilir.", "Döngü içinde koleksiyonu yanlış anda değiştirmek eleman atlamaya yol açabilir.", "Rapor satırları, toplamlar ve kullanıcı listeleri üzerinde işlem yapabilirsiniz.", "1 ile 10 arasındaki çift sayıların toplamını hesaplayın.", "toplam = 0\nfor n in range(1, 11):\n    if n % 2 == 0:\n        toplam += n\nprint(toplam)", ["for i in range(5):\n    print(i * i)", "sayac = 3\nwhile sayac > 0:\n    print(sayac)\n    sayac -= 1", "adlar = ['Ada', 'Can']\nfor indeks, ad in enumerate(adlar, start=1):\n    print(indeks, ad)", "for n in range(10):\n    if n % 2:\n        continue\n    print(n)", "for n in range(10):\n    if n == 4:\n        break\n    print(n)"]),
  M("functions", "Fonksiyonlar", "def, parametre ve return", "Tekrarlanan davranışı isimlendirir ve kapsüller.", "Fonksiyonun sorumluluğu, girdileri ve dönüş değeri yazılmadan önce belirlenmelidir.", "Varsayılan parametreler, konumlu ve anahtar kelimeli argümanlar esnek ama anlaşılır API kurar.", "Değiştirilebilir varsayılan değer aynı çağrılar arasında paylaşılabilir.", "Fonksiyon içinde print etmek yerine değer döndürmek yeniden kullanımı artırır.", "Hesaplamaları, doğrulayıcıları ve dönüştürücüleri test edilebilir parçalara ayırabilirsiniz.", "İki sayı alan, küçük olanı döndüren ve eşitliği yöneten fonksiyon yazın.", "def kucuk(a, b):\n    return a if a <= b else b\nprint(kucuk(4, 9))", ["def selam(isim, tekrar=1):\n    return (f'Merhaba {isim}! ' * tekrar).strip()\nprint(selam('Deniz', 2))", "def kare(n):\n    return n * n\nprint(kare(6))", "def topla(*sayilar):\n    return sum(sayilar)\nprint(topla(2, 3, 4))", "def ayir(ad, **bilgi):\n    return ad, bilgi\nprint(ayir('Ece', sehir='Ankara'))", "def ekle(deger, hedef=None):\n    hedef = [] if hedef is None else hedef\n    hedef.append(deger)\n    return hedef\nprint(ekle(1))"]),
  M("modules", "Modüller", "import ve paketler", "Kodu dosyalara ve yeniden kullanılabilir birimlere böler.", "İçe aktarılan adların nereden geldiğini ve modülün yan etkilerini bilmek gerekir.", "Standart kütüphane, kendi modülleriniz ve üçüncü taraf paketler farklı bağımlılık düzeyleridir.", "İsim çakışması ve döngüsel importlar tasarım sorununa işaret eder.", "Yıldızlı import kullanımı hangi adın nereden geldiğini gizler.", "Tarih, matematik ve yardımcı fonksiyonları düzenli modüllere ayırabilirsiniz.", "math ile bir dairenin alanını hesaplayın ve sonucu iki ondalık basamakla yazın.", "import math\nyaricap = 3\nprint(round(math.pi * yaricap ** 2, 2))", ["import math\nprint(math.sqrt(81))", "from datetime import date\nprint(date.today().year)", "import random\nprint(random.choice(['mavi', 'yeşil', 'sarı']))", "def ana():\n    print('çalıştı')\nif __name__ == '__main__':\n    ana()", "import statistics\nprint(statistics.mean([3, 5, 7]))"]),
  M("oop", "Nesne Tabanlı Programlama", "class ve instance", "Veri ile davranışı aynı modelde birleştirir.", "Nesne sınırını gerçek dünyadaki isimlere göre değil, değişen sorumluluklara göre çizin.", "Yapıcı, örnek niteliği, metot, kalıtım ve bileşim farklı tasarım ihtiyaçlarını karşılar.", "Paylaşılan sınıf niteliğini yanlışlıkla örnek verisi sanmak beklenmeyen sonuç verir.", "Gereksiz kalıtım sıkı bağımlılık yaratır; çoğu zaman bileşim daha esnektir.", "Sipariş, kullanıcı, oyun karakteri veya envanter modelini kapsülleyebilirsiniz.", "Bakiye yatırma ve negatif tutarı reddetme davranışı olan Hesap sınıfı yazın.", "class Hesap:\n    def __init__(self, bakiye=0):\n        self.bakiye = bakiye\n    def yatir(self, tutar):\n        if tutar > 0:\n            self.bakiye += tutar\nhesap = Hesap()\nhesap.yatir(50)\nprint(hesap.bakiye)", ["class Oyuncu:\n    def __init__(self, ad):\n        self.ad = ad\nprint(Oyuncu('Ali').ad)", "class Sayac:\n    def __init__(self):\n        self.deger = 0\n    def arttir(self):\n        self.deger += 1", "class Hayvan:\n    def ses(self):\n        return 'ses'\nclass Kedi(Hayvan):\n    def ses(self):\n        return 'miyav'\nprint(Kedi().ses())", "class Urun:\n    def __init__(self, ad, fiyat):\n        self.ad, self.fiyat = ad, fiyat\n    def indirimli(self, oran):\n        return self.fiyat * (1 - oran)", "oyuncu = Oyuncu('Ada')\nprint(isinstance(oyuncu, Oyuncu))"]),
  M("errors", "Hatalar ve İstisnalar", "try, except, else ve finally", "Beklenen başarısızlıkları kontrollü davranışa dönüştürür.", "Hatanın türünü, kullanıcıya gösterilecek mesajı ve kurtarma yolunu ayrı düşünün.", "Belirli istisnayı yakalamak, else ile başarılı yolu ayırmak ve finally ile temizlik yapmak güvenilir akış sağlar.", "Çok geniş Exception yakalama gerçek programlama hatalarını maskeleyebilir.", "Hata mesajını yok etmek yerine bağlamı koruyun ve uygun istisnayı yeniden yükseltin.", "Form dönüşümleri, API yanıtları ve kullanıcı girdileri için dayanıklı akışlar yazabilirsiniz.", "Metni tam sayıya dönüştürün; geçersizse kullanıcıya anlaşılır mesaj yazın.", "metin = '12'\ntry:\n    print(int(metin))\nexcept ValueError:\n    print('Geçerli sayı girin')", ["try:\n    sonuc = 10 / 2\nexcept ZeroDivisionError:\n    print('Sıfıra bölünemez')", "try:\n    sayi = int('x')\nexcept ValueError as hata:\n    print(type(hata).__name__)", "try:\n    deger = 5\nexcept Exception:\n    deger = 0\nelse:\n    print('başarılı:', deger)", "try:\n    print('işlem')\nfinally:\n    print('temizlik')", "yas = -1\nif yas < 0:\n    raise ValueError('Yaş negatif olamaz')"]),
  M("files", "Dosya İşlemleri", "dosya okuma ve yazma", "Kalıcı metin verisini güvenli biçimde işler.", "Dosya modu, karakter kodlaması ve kapanma sorumluluğu her işlemde açık olmalıdır.", "with bağlam yöneticisi kaynak temizliğini; satır satır okuma ise bellek kullanımını yönetir.", "Yanlış modla yazmak mevcut içeriği silebilir; büyük dosyayı tamamen belleğe almak maliyetlidir.", "Tarayıcı laboratuvarı dosya erişimini engeller; burada metin ve koleksiyon simülasyonları kullanın.", "Yerel uygulamada günlük, yapılandırma ve CSV benzeri metinleri işleyebilirsiniz.", "Bir metin listesindeki boş satırları çıkarıp numaralı biçimde yazdırın.", "satirlar = ['Python\\n', '\\n', 'Akademi\\n']\nfor sira, satir in enumerate(satirlar, 1):\n    if satir.strip():\n        print(sira, satir.strip())", ["# Gerçek ortam örneği:\n# with open('notlar.txt', encoding='utf-8') as dosya:\n#     print(dosya.read())\nprint('Laboratuvarda dosya erişimi kapalı')", "metin = 'Python Akademisi\\n'\nprint(metin.strip())", "satirlar = ['a\\n', 'b\\n']\nprint([s.strip() for s in satirlar])", "icerik = 'ad,puan\\nEce,90'\nprint(icerik.splitlines())", "veri = ['bir', 'iki']\nprint('\\n'.join(veri))"]),
  M("builtins", "Gömülü Fonksiyonlar", "len, range, zip, map ve filter", "Python'un hazır araçlarıyla ifadeyi sadeleştirir.", "Her gömülü fonksiyonun dönüş türünü ve tembel/eager davranışını kontrol edin.", "enumerate, zip, sorted, any ve all gibi araçlar açık döngüleri okunur hale getirir.", "map veya filter sonucunu doğrudan liste sanmak sürüme ve bağlama göre şaşırtabilir.", "Kısa kod için okunabilirliği feda etmeyin; anlaşılır döngü bazen daha iyidir.", "Not listelerini, paralel verileri ve doğrulama sonuçlarını işleyebilirsiniz.", "İki listenin aynı uzunlukta olup olmadığını zip ve uzunlukla denetleyin.", "a = [1, 2]\nb = ['a', 'b']\nprint(len(a) == len(b))", ["print(len('Python'))", "print(list(range(2, 8, 2)))", "adlar = ['Ada', 'Can']\npuanlar = [90, 80]\nprint(list(zip(adlar, puanlar)))", "sayilar = [1, 2, 3]\nprint(list(map(lambda n: n * 2, sayilar)))", "print(all(n > 0 for n in [1, 2, 3]))"]),
  M("collections", "İleri Seviye Veri Yapıları", "Counter, defaultdict ve deque", "Özel koleksiyonlarla niyeti ve performansı iyileştirir.", "Standart dict/list yeterli değilse collections içindeki türlerin sözleşmesine bakın.", "Counter sayma, defaultdict eksik anahtar, deque iki uçlu kuyruk işlemleri için uygundur.", "Varsayılan fabrika fonksiyonu yanlış seçilirse veri şekli beklentiyi karşılamaz.", "Sırf araç yeni diye kullanmayın; veri modelini önce basit biçimde açıklayın.", "Etiket frekansı, gruplama ve işlem kuyruğu tasarlayabilirsiniz.", "Bir cümledeki kelimeleri sayıp en sık kelimeyi bulun.", "metin = 'python ile python öğren'\nkelimeler = metin.split()\nprint(max(set(kelimeler), key=kelimeler.count))", ["from collections import Counter\nprint(Counter('aabca'))", "from collections import defaultdict\ngruplar = defaultdict(list)\ngruplar['web'].append('Flask')\nprint(dict(gruplar))", "from collections import deque\nkuyruk = deque(['ilk'])\nkuyruk.append('son')\nprint(kuyruk.popleft())", "notlar = {'Ada': [80, 90]}\nprint(notlar.get('Can', []))", "sayilar = [2, 2, 3]\nprint({n: sayilar.count(n) for n in set(sayilar)})"]),
  M("sqlite", "SQLite Veritabanı", "SQL ve sqlite3", "İlişkisel veriyi sorgulanabilir biçimde saklar.", "Tablo şemasını, anahtarları ve sorgu parametrelerini tasarımın başında düşünün.", "CREATE, INSERT, SELECT ve commit işlemleri kalıcı veri akışının temelidir.", "Metin birleştirerek SQL yazmak güvenlik ve tırnak hatalarına açıktır.", "Laboratuvarda dış veritabanı erişimi yerine SQL düşüncesini koleksiyonlarla simüle edin.", "Görev, öğrenci veya ürün kayıtlarını kalıcı bir uygulamada modelleyebilirsiniz.", "Ürün listesinde fiyatı 100'den büyük kayıtları filtreleyen bir simülasyon kurun.", "urunler = [{'ad': 'kitap', 'fiyat': 80}, {'ad': 'klavye', 'fiyat': 120}]\nprint([u['ad'] for u in urunler if u['fiyat'] > 100])", ["sql = 'SELECT ad FROM ogrenci WHERE puan > ?'\nprint(sql)", "kayit = ('Ece', 90)\nprint(kayit[0], kayit[1])", "satirlar = [('Ada', 80), ('Can', 95)]\nfor ad, puan in satirlar:\n    print(ad, puan)", "tablo = [{'id': 1, 'ad': 'Not'}]\nprint(tablo[0]['id'])", "sorgu = 'INSERT INTO notlar(ad, puan) VALUES (?, ?)'\nprint(sorgu)"]),
  M("decorators", "Decoratorlar", "@decorator", "Fonksiyon davranışını sarmalayarak genişletir.", "Sarmalayıcının giriş, çıkış ve fonksiyon metaverisi üzerindeki etkisini görün.", "Closure, *args/**kwargs ve functools.wraps decorator tasarımının temel parçalarıdır.", "Yan etkili decoratorlar test sırasını ve hata izini zorlaştırabilir.", "wraps kullanmadan orijinal fonksiyon adı ve dokümantasyonu kaybolabilir.", "Zamanlama, yetki denetimi ve kayıt alma gibi çapraz kesen davranışları ekleyebilirsiniz.", "Bir fonksiyondan önce ve sonra mesaj yazdıran decorator oluşturun.", "def duyur(f):\n    def sar():\n        print('başlıyor')\n        f()\n        print('bitti')\n    return sar\n@duyur\ndef merhaba():\n    print('merhaba')\nmerhaba()", ["def vurgu(f):\n    def sar(*args):\n        return f(*args).upper()\n    return sar", "@vurgu\ndef selam(ad):\n    return f'merhaba {ad}'\nprint(selam('Ece'))", "def iki_kat(f):\n    return lambda n: f(n) * 2", "def yetki(f):\n    def sar(rol):\n        return f(rol) if rol == 'admin' else 'yasak'\n    return sar", "def kimlik(f):\n    return f\nprint(kimlik(lambda: 'ok')())"]),
  M("iterators", "Iteratorlar ve Generatorlar", "iter, next ve yield", "Veriyi gerektiğinde üreterek bellek kullanımını sınırlar.", "Iterable ile iterator arasındaki farkı; generatorın tek geçişli doğasını bilin.", "yield fonksiyonu duraklatır, durumunu korur ve sonraki değerde devam eder.", "Tüketilmiş generator ikinci kez aynı değerleri vermez.", "Generator sonucunu tekrar kullanacaksanız yeniden üretin veya bilinçli biçimde listeye alın.", "Büyük kayıt akışları, sayfalama ve ardışık hesaplamalar kurabilirsiniz.", "0'dan başlayarak beş çift sayı üreten generator yazın.", "def ciftler():\n    for n in range(10):\n        if n % 2 == 0:\n            yield n\nprint(list(ciftler()))", ["sayilar = iter([10, 20])\nprint(next(sayilar))", "def sayac(son):\n    for n in range(son):\n        yield n\nprint(list(sayac(3)))", "kareler = (n * n for n in range(4))\nprint(list(kareler))", "for deger in iter('abc'):\n    print(deger)", "print(sum(n for n in range(5)))"]),
  M("adv_modules", "İleri Seviye Modüller", "datetime, re, json ve pathlib", "Standart kütüphanenin güçlü araçlarını doğru bağlamda kullanır.", "Modül seçerken veri formatı, zaman dilimi ve hata davranışı gibi sınırları belirleyin.", "JSON serileştirme, düzenli ifade ve tarih işlemleri farklı veri temsil kuralları taşır.", "Tarihi metin gibi karşılaştırmak veya regex'i doğrulamasız kullanmak kırılgandır.", "Veri formatını ve tarih bölgesini açıkça belirtin; karmaşık regex'i test edin.", "Yapılandırma, tarihli rapor ve metin doğrulama işlemleri geliştirebilirsiniz.", "Bir sözlüğü JSON metnine çevirip geri okuyun.", "import json\nveri = {'ad': 'Ece', 'aktif': True}\nmetin = json.dumps(veri)\nprint(json.loads(metin)['ad'])", ["import json\nprint(json.dumps({'puan': 90}))", "import re\nprint(bool(re.fullmatch(r'\\d{4}', '2026')))", "from datetime import date\nprint(date(2026, 1, 1).isoformat())", "from pathlib import PurePath\nprint(PurePath('veri/notlar.csv').suffix)", "import statistics\nprint(statistics.median([1, 3, 9]))"]),
  M("pyqt", "PyQt5", "widget, signal ve slot", "Masaüstü arayüzlerini olay odaklı tasarlar.", "Arayüz durumunu, görünümü ve olay işleyicilerini birbirinden ayırın.", "Widget hiyerarşisi, layout, signal-slot bağlantısı ve event loop PyQt uygulamasının omurgasıdır.", "Uzun işlerin ana arayüz iş parçacığında yapılması pencereyi dondurur.", "PyQt laboratuvarda çalışmaz; örnekleri kavramsal olarak inceleyin ve yerelde deneyin.", "Form, yapılacaklar listesi veya veri giriş arayüzü tasarlayabilirsiniz.", "Bir düğme tıklanınca etiketi güncelleyen akışı sözlü olarak açıklayın.", "durum = 'Hazır'\ndef tiklandi():\n    return 'Kaydedildi'\nprint(durum, '->', tiklandi())", ["# PyQt: button.clicked.connect(kaydet)\nsinyal = 'clicked'\nprint(sinyal)", "form = {'ad': '', 'email': ''}\nform['ad'] = 'Ece'\nprint(form)", "def dogrula(metin):\n    return bool(metin.strip())\nprint(dogrula('  Ada '))", "durumlar = ['Hazır', 'Kaydediliyor', 'Tamam']\nfor durum in durumlar:\n    print(durum)", "hata = None\nprint('Mesaj:', hata or 'İşlem başarılı')"]),
  M("level2", "Python Kursu 2. Seviye", "profesyonel Python alışkanlıkları", "Temelleri projeye dönüştürme aşamasıdır.", "İkinci seviyede asıl kazanım araç listesinden çok problem çözme disiplinidir.", "Tip ipuçları, test, paket yapısı ve hata kayıtları daha güvenilir kod üretmeyi destekler.", "Her şeyi bir dosyada tutmak büyüyen projede yön kaybı yaratır.", "Küçük bir proje sınırı belirleyin; çalışır sürümü kurup adım adım iyileştirin.", "Komut satırı bağımsız küçük bir kural motoru veya not uygulaması geliştirebilirsiniz.", "Bir puanı 0-100 aralığına sıkıştıran fonksiyon yazın.", "def sinirla(puan):\n    return max(0, min(100, puan))\nprint(sinirla(120))", ["def topla(a: int, b: int) -> int:\n    return a + b\nprint(topla(2, 3))", "def test_kare():\n    assert 4 * 4 == 16\ntest_kare()", "ayarlar = {'tema': 'koyu'}\nprint(ayarlar['tema'])", "sonuclar = [80, 90, 70]\nprint(sum(sonuclar) / len(sonuclar))", "def temiz(metin):\n    return metin.strip().lower()\nprint(temiz(' PYTHON '))"]),
  M("flask", "Flask Web", "route, request ve response", "HTTP isteklerini Python fonksiyonlarına bağlar.", "Endpoint'in URL'sini, metodunu, girişini ve dönüş biçimini açıkça tasarlayın.", "Flask route, template, request ve response kavramlarıyla küçük web uygulamaları kurar.", "Girdi doğrulanmadan doğrudan işlenirse hatalı veya güvensiz sonuçlar oluşur.", "Tarayıcı laboratuvarında sunucu başlatılmaz; HTTP akışını saf Python örnekleriyle modelleyin.", "Sayfa, form işleme ve JSON döndüren küçük endpointler tasarlayabilirsiniz.", "Bir isim parametresinden karşılama yanıtı üreten fonksiyon yazın.", "def merhaba(ad):\n    ad = ad.strip() or 'misafir'\n    return {'mesaj': f'Merhaba {ad}'}\nprint(merhaba('Ece'))", ["istek = {'method': 'GET', 'args': {'ad': 'Ada'}}\nprint(istek['args']['ad'])", "def yanit(veri, durum=200):\n    return {'status': durum, 'body': veri}\nprint(yanit({'ok': True}))", "yollar = {'/': 'ana_sayfa', '/api': 'api'}\nprint(yollar['/api'])", "form = {'email': 'a@b.com'}\nprint(bool(form.get('email')))", "def hata(mesaj):\n    return {'error': mesaj}, 400\nprint(hata('geçersiz istek'))"]),
  M("sqlalchemy", "Flask ORM SqlAlchemy Todo", "ORM, model ve sorgu", "Veritabanı tablolarını Python nesneleriyle eşler.", "Model alanları ve iş kuralları veritabanı şemasının okunur karşılığıdır.", "ORM ile model, oturum, sorgu ve transaction kavramları birlikte çalışır.", "Transaction tamamlanmadan yapılan değişiklik kalıcı sayılmaz.", "N+1 sorgu sorunu büyüyen listelerde performansı ciddi biçimde etkiler.", "Todo öğelerini oluşturma, tamamlama ve filtreleme özellikleri geliştirebilirsiniz.", "Tamamlanmamış görevleri filtreleyen bir liste işlemi yazın.", "gorevler = [{'ad': 'Oku', 'tamam': True}, {'ad': 'Yaz', 'tamam': False}]\nprint([g['ad'] for g in gorevler if not g['tamam']])", ["model = {'id': 1, 'baslik': 'Öğren'}\nprint(model['baslik'])", "gorev = {'tamam': False}\ngorev['tamam'] = True\nprint(gorev)", "kayitlar = [{'id': 1}, {'id': 2}]\nprint(next(k for k in kayitlar if k['id'] == 2))", "def dogrula_baslik(baslik):\n    return len(baslik.strip()) >= 3\nprint(dogrula_baslik('Kod'))", "oturum_degisti = True\nprint('commit' if oturum_degisti else 'bekle')"]),
  M("django", "Django Web", "model, view, template ve URL", "Düzenli web uygulamaları için güçlü bir mimari sunar.", "Uygulama sınırlarını ve verinin yaşam döngüsünü başlangıçta netleştirin.", "Django ORM, URL yönlendirme, view ve template katmanlarını bütünler.", "View içine aşırı iş mantığı koymak tekrar ve test zorluğu doğurur.", "CSRF ve yetkilendirme kontrollerini form akışında atlamayın.", "Blog, envanter veya üyelik içeren çok sayfalı uygulamalar kurabilirsiniz.", "Yayınlanmış makaleleri filtreleyen saf Python görünümü yazın.", "makaleler = [{'baslik': 'Python', 'yayin': True}, {'baslik': 'Taslak', 'yayin': False}]\nprint([m['baslik'] for m in makaleler if m['yayin']])", ["urlconf = {'/makaleler/': 'makale_listesi'}\nprint(urlconf)", "baglam = {'baslik': 'Akademi'}\nprint(f\"<h1>{baglam['baslik']}</h1>\")", "form = {'baslik': 'Yeni yazı'}\nprint(form['baslik'].strip())", "kullanici = {'giris_yapti': True}\nprint('göster' if kullanici['giris_yapti'] else 'giriş yap')", "model = {'slug': 'python-giris'}\nprint('/yazi/' + model['slug'])"]),
  M("deploy_flask", "Flask Deploy", "WSGI, environment ve production", "Flask uygulamasını güvenli üretim ortamına taşır.", "Yerel geliştirme ile üretim varsayımlarını kesin biçimde ayırın.", "WSGI sunucusu, ters proxy, çevre değişkeni ve loglar dağıtımın temel bileşenidir.", "Debug modunu ve gizli anahtarları üretimde açık bırakmak güvenlik riskidir.", "Sırları kaynak koduna yazmayın; yapılandırmayı çevre değişkeniyle yönetin.", "Bir Flask uygulaması için çalıştırma komutu, sağlık kontrolü ve yapılandırma planlayabilirsiniz.", "Gerekli ayarları doğrulayan saf Python yapılandırma fonksiyonu yazın.", "ayarlar = {'DEBUG': False, 'SECRET_KEY': 'ortamdan-gelir'}\nprint('Hazır' if not ayarlar['DEBUG'] else 'Riskli')", ["ortam = {'PORT': '8000'}\nprint(int(ortam['PORT']))", "def saglik():\n    return {'status': 'ok'}\nprint(saglik())", "log = {'seviye': 'INFO', 'mesaj': 'başladı'}\nprint(log)", "ayar = {'debug': False}\nassert ayar['debug'] is False", "alan_adi = 'example.com'\nprint('https://' + alan_adi)"]),
  M("deploy_django", "Django Deploy", "settings, static files ve migration", "Django projesini üretim gereksinimleriyle yapılandırır.", "Ayarları ortam bazlı tutun; güvenlik, statik dosya ve veritabanını ayrı doğrulayın.", "ALLOWED_HOSTS, DEBUG, static dosyalar, migration ve WSGI/ASGI yayın sürecinin parçalarıdır.", "Migration çalıştırmadan şema değişikliği yayınlamak uygulamayı bozabilir.", "DEBUG=True ve boş ALLOWED_HOSTS üretim ayarı değildir.", "Django siteniz için yayın kontrol listesi ve geri dönüş planı oluşturabilirsiniz.", "Üretim ayarlarında debug değerini denetleyen bir kontrol yazın.", "settings = {'DEBUG': False, 'ALLOWED_HOSTS': ['ornek.com']}\nprint(bool(settings['ALLOWED_HOSTS']) and not settings['DEBUG'])", ["staticler = ['css/site.css', 'js/app.js']\nprint(len(staticler))", "migration = {'uygulandi': True}\nprint('tamam' if migration['uygulandi'] else 'bekliyor')", "hosts = ['ornek.com']\nprint('ornek.com' in hosts)", "def guvenli_mi(debug):\n    return debug is False\nprint(guvenli_mi(False))", "surum = '2026.07'\nprint('release', surum)"]),
  M("selenium", "Selenium Ekşi Sözlük", "WebDriver ve locator", "Tarayıcı otomasyonunun temel akışını öğretir.", "Otomasyonu insan gibi tıklama değil, kararlı seçiciler ve beklemeler olarak tasarlayın.", "Driver, locator, explicit wait ve sayfa nesnesi yaklaşımı sağlam testlerin temelidir.", "Sabit sleep kullanımı yavaş ve kararsız testler üretir.", "Sitenin kullanım koşullarına uyun; otomasyonu yetkisiz veri çekme veya spam için kullanmayın.", "Arama sayfası testi ve sonuç başlığı doğrulaması tasarlayabilirsiniz.", "Bir arama sonucunda beklenen başlığın bulunduğunu denetleyen saf fonksiyon yazın.", "basliklar = ['Python', 'JavaScript']\nprint('Python' in basliklar)", ["secici = \"css selector: input[name='q']\"\nprint(secici)", "durum = {'yuklendi': True}\nprint(durum['yuklendi'])", "def metin_var_mi(metin, beklenen):\n    return beklenen.lower() in metin.lower()\nprint(metin_var_mi('Python öğren', 'python'))", "sonuclar = ['bir', 'iki']\nassert len(sonuclar) > 0", "test_adi = 'arama_sonucu'\nprint(test_adi)"]),
  M("selenium2", "Selenium Twitter", "sayfa nesnesi ve bekleme", "Dinamik web arayüzlerinde güvenilir otomasyon kurar.", "Kimlik doğrulama ve dinamik içerik için test verisi ile gerçek hesabı ayırın.", "Explicit wait, görünürlük kontrolü ve soyut sayfa nesneleri test bakımını azaltır.", "Kırılgan XPath ve zamanlamaya bağlı tıklamalar testleri rastgele başarısız yapar.", "Platform kuralları ile API tercihlerini gözden geçirin; kişisel veri toplamaktan kaçının.", "Bir paylaşım formu için alan doğrulama test senaryosu yazabilirsiniz.", "Gönderi metninin boş olmadığını ve limit altında kaldığını denetleyin.", "def gecerli_gonderi(metin):\n    return 0 < len(metin.strip()) <= 280\nprint(gecerli_gonderi('Python öğreniyorum'))", ["limit = 280\nprint(len('merhaba') <= limit)", "form = {'metin': 'Selam'}\nprint(form['metin'])", "bekleme = {'buton_gorunur': True}\nprint(bekleme['buton_gorunur'])", "def secici_olustur(testid):\n    return f'[data-testid=\"{testid}\"]'\nprint(secici_olustur('tweetButton'))", "sonuc = {'basarili': True}\nassert sonuc['basarili']"]),
  M("selenium3", "Selenium Instagram", "dinamik içerik testi", "Görsel ağırlıklı uygulamalarda kullanıcı akışını doğrular.", "Testi kullanıcı niyeti üzerinden yazın: giriş, görüntüleme, doğrulama ve çıkış.", "Element görünürlüğü, metin eşleşmesi ve hata durumları otomasyonun doğrulama katmanıdır.", "Kişisel hesaplar veya korumalı sayfalar üzerinde izinsiz otomasyon etik ve hukuki sorun yaratır.", "Gizli verileri test koduna koymayın; yetkili test hesabı ve güvenli secret yönetimi kullanın.", "Profil bilgisi ve gönderi açıklaması için görüntüleme senaryoları tasarlayabilirsiniz.", "Bir açıklamanın maksimum uzunluğunu ve boşluk durumunu doğrulayın.", "def gecerli_aciklama(metin):\n    return 0 < len(metin.strip()) <= 2200\nprint(gecerli_aciklama('Yeni proje'))", ["profil = {'kullanici': 'akademi'}\nprint(profil['kullanici'])", "gonderi = {'begeni': 12}\nprint(gonderi['begeni'])", "def gorunur_mu(eleman):\n    return eleman.get('gorunur', False)\nprint(gorunur_mu({'gorunur': True}))", "etiketler = ['python', 'kodlama']\nprint('#' + ' #'.join(etiketler))", "assert gecerli_aciklama('Merhaba')"]),
  M("flask_api", "Flask Fixer.io Döviz", "REST API ve JSON", "Harici veriyle çalışan web endpointleri tasarlar.", "API sözleşmesini kaynak, dönüş şeması, hata ve önbellek boyutlarıyla tanımlayın.", "JSON, HTTP durum kodları, parametre doğrulama ve kur dönüşümü bu modülün ana araçlarıdır.", "Harici servisin başarısız olabileceğini veya kurun eksik olabileceğini hesaba katın.", "API anahtarını istemciye veya kaynak koda gömmeyin; oranların zaman damgasını gösterin.", "Para birimi dönüştürücü endpointi ve hata yanıtları geliştirebilirsiniz.", "Tutar ve kurla dönüştürme yapan bir fonksiyon yazın.", "def cevir(tutar, kur):\n    if tutar < 0 or kur <= 0:\n        return None\n    return round(tutar * kur, 2)\nprint(cevir(100, 0.92))", ["yanit = {'base': 'EUR', 'rates': {'TRY': 35.2}}\nprint(yanit['rates']['TRY'])", "def api_yanit(veri):\n    return {'data': veri, 'status': 200}\nprint(api_yanit({'ok': True}))", "kod = 404\nprint('bulunamadı' if kod == 404 else 'tamam')", "para = {'miktar': 10, 'birim': 'USD'}\nprint(para)", "oranlar = {'USD': 1.0, 'EUR': 0.92}\nprint(oranlar.get('EUR'))"]),
  M("github_api", "Github REST API", "REST kaynakları ve pagination", "GitHub verisini resmi API sözleşmesine göre işler.", "Kaynak URL'si, kimlik doğrulama kapsamı ve hız sınırı uygulama davranışını belirler.", "Repository, kullanıcı, issue ve sayfalama yanıtlarını JSON üzerinden dikkatle okuyun.", "Rate limit veya 404 yanıtını başarılı veri gibi işlemek yanıltıcı arayüz üretir.", "Token'a en az yetki verin ve asla frontend kaynak koduna yazmayın.", "Kullanıcı deposu listesi ve yıldız sayılarını gösteren istemci mantığı kurabilirsiniz.", "Depo nesnelerinden yıldızı 100'den fazla olan adları çıkarın.", "depolar = [{'ad': 'a', 'star': 120}, {'ad': 'b', 'star': 4}]\nprint([d['ad'] for d in depolar if d['star'] > 100])", ["repo = {'name': 'python', 'stargazers_count': 99}\nprint(repo['name'])", "sayfa = {'next': 2, 'items': [1, 2]}\nprint(sayfa['next'])", "durum = 403\nprint('limit' if durum == 403 else 'devam')", "def url(kullanici):\n    return f'/users/{kullanici}/repos'\nprint(url('octocat'))", "headers = {'Accept': 'application/json'}\nprint(headers)"]),
  M("scrapy", "Scrapy kitapyurdu", "spider, selector ve item", "Web verisini sorumlu ve ölçeklenebilir biçimde toplar.", "Önce izinleri, robots politikasını ve veri gereksinimini doğrulayın.", "Spider istek üretir, selector yanıtı ayrıştırır, item yapılandırılmış sonucu taşır.", "Sayfa yapısına aşırı bağlı seçiciler küçük tasarım değişikliğinde bozulur.", "Kişisel veri, telif ve site koşullarını ihlal edecek scraping yapmayın.", "İzinli katalog verisini ürün adı ve fiyat olarak yapılandırabilirsiniz.", "Ürün sözlüğünden zorunlu alanları doğrulayan fonksiyon yazın.", "def gecerli_urun(urun):\n    return bool(urun.get('ad')) and urun.get('fiyat', 0) > 0\nprint(gecerli_urun({'ad': 'Kitap', 'fiyat': 120}))", ["html_veri = {'baslik': 'Python Kitabı'}\nprint(html_veri['baslik'])", "urun = {'ad': 'Kitap', 'fiyat': 120}\nprint(urun)", "def temiz_fiyat(metin):\n    return float(metin.replace(' TL', '').replace(',', '.'))\nprint(temiz_fiyat('99,90 TL'))", "seciciler = ['h1.baslik', '.fiyat']\nprint(seciciler)", "sonuclar = [{'ad': 'A'}, {'ad': 'B'}]\nprint(len(sonuclar))"]),
  M("numpy", "Numpy", "ndarray ve vektörleştirme", "Sayısal diziler üzerinde hızlı toplu işlem yapar.", "Dizinin shape, dtype ve eksen kavramlarını her işlemden önce kontrol edin.", "Vektörleştirme, broadcasting ve dilimleme Python döngülerinin yerine daha yoğun işlemler sunar.", "Farklı shape'leri yanlış yayınlamak beklenmeyen sonuç veya hata üretir.", "Bu laboratuvarda NumPy kurulu olmayabilir; mantığı saf listelerle inceleyin.", "Ölçüm, matris ve sayısal özellik verisi üzerinde dönüşümler yapabilirsiniz.", "Bir sayı listesinin ortalamasını hesaplayıp her değerden çıkarın.", "sayilar = [2, 4, 6]\nortalama = sum(sayilar) / len(sayilar)\nprint([n - ortalama for n in sayilar])", ["dizi = [[1, 2], [3, 4]]\nprint(len(dizi), len(dizi[0]))", "sayilar = [1, 2, 3]\nprint([n * 10 for n in sayilar])", "satir = [1, 2, 3]\nprint(sum(satir))", "matris = [[1, 2], [3, 4]]\nprint([n for s in matris for n in s])", "veri = [3.0, 5.0]\nprint(max(veri) - min(veri))"]),
  M("pandas", "Pandas", "DataFrame ve Series", "Tablo verisini seçer, temizler ve özetler.", "Kolon türleri, eksik değerler ve satır kimliği analizden önce anlaşılmalıdır.", "Filtreleme, groupby, merge ve describe veri analizinin tekrar eden yapı taşlarıdır.", "Eksik değeri sessizce sıfır kabul etmek analizi çarpıtabilir.", "DataFrame kopyası ve görünümü arasındaki farkı izleyin; dönüşümü açık atayın.", "Satış, öğrenci veya anket tablolarını temizleyip özetleyebilirsiniz.", "Puanı 70 üstü öğrencilerin adlarını listeleyen işlem yazın.", "ogrenciler = [{'ad': 'Ada', 'puan': 80}, {'ad': 'Can', 'puan': 60}]\nprint([o['ad'] for o in ogrenciler if o['puan'] >= 70])", ["satirlar = [{'sehir': 'Ankara'}, {'sehir': 'İzmir'}]\nprint(len(satirlar))", "puanlar = [80, 90, 70]\nprint(sum(puanlar) / len(puanlar))", "veri = [{'kategori': 'A', 'tutar': 10}, {'kategori': 'A', 'tutar': 5}]\nprint(sum(x['tutar'] for x in veri if x['kategori'] == 'A'))", "eksik = [1, None, 3]\nprint([x for x in eksik if x is not None])", "kolonlar = ['ad', 'puan']\nprint(', '.join(kolonlar))"]),
  M("pandas_proj", "US Soccer Salaries Analysis", "keşifsel veri analizi", "Maaş verisini soruyla başlayan bir analiz sürecine dönüştürür.", "Analiz sorusunu önce tanımlayın: ortalama mı, dağılım mı, pozisyon farkı mı?", "Temizleme, aykırı değer inceleme, gruplama ve yorumlama birbirinden ayrı adımlardır.", "Ortalama tek başına uç maaşların etkisini gizleyebilir.", "Eksik ücret ve para birimi varsayımlarını raporda açıkça belirtin.", "Lig, pozisyon ve maaş ilişkisini etik biçimde özetleyen bir analiz üretebilirsiniz.", "Pozisyonlara göre ortalama maaşı hesaplayan bir simülasyon yazın.", "oyuncular = [{'pozisyon': 'F', 'maas': 100}, {'pozisyon': 'F', 'maas': 200}, {'pozisyon': 'D', 'maas': 80}]\nfor p in {'F', 'D'}:\n    degerler = [o['maas'] for o in oyuncular if o['pozisyon'] == p]\n    print(p, sum(degerler) / len(degerler))", ["maaslar = [80, 100, 200]\nprint(sum(maaslar) / len(maaslar))", "print(sorted([200, 80, 100]))", "veri = [{'takim': 'A', 'maas': 100}]\nprint(veri[0]['takim'])", "aykiri = [50, 55, 900]\nprint(max(aykiri))", "rapor = {'orneklem': 3, 'not': 'simülasyon'}\nprint(rapor)"]),
  M("api_proj", "Youtube Video İstatistikleri Analizi", "API verisi ve metrik", "Video verisini anlamlı performans göstergelerine dönüştürür.", "Metriklerin tanımını yazın; görüntülenme, beğeni ve yorum aynı şeyi ölçmez.", "API yanıtını doğrulamak, sayfalama ve oran hesaplamak güvenilir analizin parçalarıdır.", "Sıfır görüntülenmede etkileşim oranı bölme hatası üretir.", "Quota ve gizlilik kurallarına uyun; sonuçların örneklem ve zaman aralığını belirtin.", "Video listelerini karşılaştıran ve etkileşim oranı hesaplayan analiz kurabilirsiniz.", "Görüntülenme sıfırsa None döndüren etkileşim oranı yazın.", "def etkilesim(begeni, yorum, izlenme):\n    if izlenme == 0:\n        return None\n    return round((begeni + yorum) / izlenme * 100, 2)\nprint(etkilesim(50, 10, 1000))", ["video = {'title': 'Python', 'views': 1000}\nprint(video['views'])", "istatistik = {'likes': 30, 'comments': 4}\nprint(sum(istatistik.values()))", "sayfa = {'items': [1, 2], 'nextPageToken': None}\nprint(sayfa['nextPageToken'])", "videolar = [{'views': 10}, {'views': 20}]\nprint(sum(v['views'] for v in videolar))", "tarih = '2026-07-28'\nprint(tarih)"]),
  M("matplotlib", "Matplotlib", "figure, axes ve grafik", "Veriyi doğru görsel kodlamayla anlatır.", "Grafiğin sorusunu, eksenlerini ve karşılaştırma türünü çizmeden önce belirleyin.", "Çizgi, çubuk, histogram ve saçılım grafiği farklı veri ilişkilerini gösterir.", "Kesik eksen, yanıltıcı ölçek veya etiketsiz grafik yanlış yorum doğurabilir.", "Grafiğin başlığını, birimini ve veri kaynağını her zaman görünür kılın.", "Analiz raporları için karşılaştırılabilir ve açıklanabilir görseller tasarlayabilirsiniz.", "Haftalık çalışma saatlerini metin çubuğuyla görselleştirin.", "gunler = {'Pzt': 2, 'Sal': 4, 'Çar': 3}\nfor gun, saat in gunler.items():\n    print(f'{gun}: ' + '█' * saat)", ["x = [1, 2, 3]\ny = [2, 5, 4]\nprint(list(zip(x, y)))", "baslik = 'Aylık satış'\nprint(baslik)", "degerler = [3, 5, 4]\nprint(max(degerler), min(degerler))", "etiketler = ['Ocak', 'Şubat']\nprint(', '.join(etiketler))", "def oran(n, toplam):\n    return n / toplam if toplam else 0\nprint(oran(2, 5))"]),
];

const ACADEMY_BANK = Object.fromEntries(MODULES.map((m) => [m.key, {
  lesson: lessonFor(m),
  flashcards: cardsFor(m),
  quiz: quizFor(m),
  starter: m.starter,
}]));
